Implement additional xtce keywords
OpenC3/openc3 pull request #51
Opened 2022-08-07 23:04 UTC by jmthomas

closes #12

2022-08-08 00:41 UTC, jmthomas commented
@AstreeDeshayes I would love if you could try this out and see if it works. I have some TODOs in the code because i'm not sure about conversions and such.

2022-08-08 23:55 UTC, ryanmelt requested changes

2022-08-08 23:55 UTC, ryanmelt commented on openc3/spec/packets/parsers/xtce_parser_spec.rb
> +        expect(packet.get_item('A').write_conversion.class).to eql PolynomialConversion
CRC polynomials are not polynomial conversions.  They define one of the parameters necessary for the CRC algorithm.

2022-08-08 23:55 UTC, ryanmelt commented on openc3/spec/packets/parsers/xtce_parser_spec.rb
> +        expect(packet.get_item('A').data_type).to eql :BLOCK
CRCs should be UINT I think.

2022-08-08 23:55 UTC, ryanmelt commented on openc3/lib/openc3/packets/parsers/xtce_parser.rb
> +        # TODO: Anything else here?
Not sure what to do for now, probably just leave a TODO.  We could create a new CrcProcessor to check the packet in telemetry and maybe set the Crc for commands.

2022-08-08 23:55 UTC, ryanmelt commented on openc3/lib/openc3/packets/parsers/xtce_parser.rb
> +      when 'Polynomial', 'PolynomialCalibrator'
CRC polynomial is not a conversion.

2022-08-16 07:50 UTC, AstreeDeshayes commented
> @AstreeDeshayes I would love if you could try this out and see if it works. I have some TODOs in the code because i'm not sure about conversions and such.

Hello, it still doesn't work... I tried by directly putting the xtce file into the cmd_tlm folder and also with the xtce converter command line and I have the following errors : 

Processing MDB.xtce...
  Ignoring Unknown: <AbsoluteTimeParameterType>
  Ignoring Unknown: <Encoding>
  Ignoring Unknown: <ReferenceTime>
  Ignoring Unknown: <Epoch>
  Ignoring Unknown: <ErrorDetectCorrect>
  Ignoring Unknown: <CRC>
  Ignoring Unknown: <Polynomial>
  Ignoring Unknown: <Term>
  Ignoring Unknown: <Term>
  Ignoring Unknown: <Term>
  Ignoring Unknown: <Term>
  Ignoring Unknown: <BooleanParameterType>
  Ignoring Unknown: <BooleanParameterType>

2022-08-16 17:13 UTC, merged